# This workflow will install Python dependencies, run tests of the Flask server endpoint /healthCheck

name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install Flask

    - name: Run Flask server
      run: |
        python app.py & sleep 3  # start Flask server，and wait for 3 seconds to make sure it is running

    - name: Health check
      run: |
        response=$(curl -s -o /dev/null -w "%{http_code}" http://127.0.0.1:5000/healthCheck)
        if [ $response -eq 200 ]; then
          echo "Health check passed!"
        else
          echo "Health check failed with status code: $response"
          exit 1
        fi
